name: cron job workflow

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  cron_job:
    runs-on: ubuntu-latest

    steps:
      - name: Run cron workflow
        run: echo "Hello EduHub API"
