name: Dependent Multi Job Workflow

on:
  workflow_dispatch:

jobs:
  first-workflow-job:
    runs-on: ubuntu-latest

    steps:
      - name: First workflow job
        run: |
          echo "Hello from the first workflow job"

  second-workflow-job:
    runs-on: ubuntu-latest
    needs: first-workflow-job

    steps:
      - name: Second workflow job (runs after first)
        run: |
          echo "This job runs after the first job"
